import { Rubik  } from "next/font/google";
import React from 'react';
import "./globals.css";
import i18nConfig from '@/app/i18nConfig';
import Footer from "@/components/Layout/Footer";

const inter = Rubik({
  weight: ['400', '600'],
  style: ['normal', 'italic'],
  variable: '--font-rubik',
  subsets: ['latin'],
});

export const metadata = {
  title: "Rezerve App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

export default function RootLayout({
  children, params: { locale }
}) {
  return (
    <html lang={locale}>
      <body className={inter.className}>
        <main>
          {children}
        </main>
        <div>
          <Footer />
        </div>
      </body>
    </html>
  );
}